[variables]
DATABASE_URL = "file:./prisma/dev.db"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "cd frontend && npm install && npm run build && cd ..",
  "npx tsc"
]

[start]
cmd = "npm run start"
